import { Incident } from '@/types';

export const shopflowIncidents: Incident[] = [
  {
    id: 'inc-1042',
    code: 'INV-1042',
    projectId: 'shopflow',
    title: 'Order creation degradation & checkout latency spike',
    description: 'Order creation latency increased ~11.9x (320ms → 3.8s). Primary root cause identified as payment dependency timeout retries under release v2.4.1.',
    severity: 'High',
    status: 'Investigating',
    affectedService: 'order-service',
    affectedServices: ['order-service', 'payment-service'],
    detectedAt: '14:03 UTC',
    duration: '22m',
    confidence: 91,
    updatedAt: '2m ago',
    reporter: 'Datadog Alert Manager',
    environment: 'Production',
  },
  {
    id: 'inc-1041',
    code: 'INV-1041',
    projectId: 'shopflow',
    title: 'Redis connection pool exhaustion',
    description: 'Transient spike in user session lookups caused connection pool exhaustion in user-service.',
    severity: 'Medium',
    status: 'Identified',
    affectedService: 'user-service',
    affectedServices: ['user-service', 'redis'],
    detectedAt: '11:15 UTC',
    duration: '1h 40m',
    confidence: 84,
    updatedAt: '1h ago',
    reporter: 'SRE On-Call',
    environment: 'Production',
  },
  {
    id: 'inc-1040',
    code: 'INV-1040',
    projectId: 'shopflow',
    title: 'Inventory batch sync lock contention',
    description: 'Nightly catalog synchronization worker held row locks on inventory items for 45s.',
    severity: 'Low',
    status: 'Resolved',
    affectedService: 'inventory-service',
    affectedServices: ['inventory-service', 'postgres'],
    detectedAt: '03:00 UTC',
    duration: '12m',
    confidence: 98,
    updatedAt: '11h ago',
    reporter: 'CronJob Monitor',
    environment: 'Production',
  },
];
