import { Investigation, KnowledgeDocument, EvidenceItem, LogEvent } from '@/types';

export const shopflowInvestigations: Record<string, Investigation> = {
  'inc-1042': {
    id: 'inv-1042',
    incidentId: 'inc-1042',
    title: 'Order creation degradation',
    status: 'analyzing',
    severity: 'High',
    confidence: 91,
    summary:
      'Order creation latency increased approximately 11.9x beginning around 14:03 UTC. Evidence indicates the primary degradation originates from the payment dependency timeout retries under release v2.4.1.',
    impact: {
      affectedFunctionality: 'Checkout & Order Creation',
      affectedServices: ['order-service', 'payment-service'],
      estimatedImpact: '~1,200 checkout sessions delayed, 12.4% error rate',
      startTime: '14:03 UTC',
      currentDuration: '22m',
    },
    detectedChanges: [
      {
        id: 'mc-1',
        name: 'Order creation latency (P95)',
        baseline: '320 ms',
        current: '3.8 s',
        percentChange: '+1087%',
        isNegative: true,
      },
      {
        id: 'mc-2',
        name: 'Payment service latency (P95)',
        baseline: '500 ms',
        current: '3.5 s',
        percentChange: '+600%',
        isNegative: true,
      },
      {
        id: 'mc-3',
        name: 'Checkout HTTP 504 error rate',
        baseline: '0.7%',
        current: '12.4%',
        percentChange: '+1671%',
        isNegative: true,
      },
      {
        id: 'mc-4',
        name: 'Postgres query duration',
        baseline: '4.6 ms',
        current: '5.1 ms',
        percentChange: '+10%',
        isNegative: false,
      },
    ],
    primaryHypothesis: {
      id: 'hyp-1',
      investigationId: 'inv-1042',
      title: 'Payment dependency degradation & retry amplification',
      description:
        'Payment gateway latency spiked to 3.5s at 13:55 UTC. Combined with release v2.4.1 retry configuration increase (from 2 to 5 retries), order-service thread pools saturated.',
      confidenceLabel: 'HIGH',
      probability: 0.91,
      status: 'primary',
      evidenceItems: [
        { id: 'ev-1', text: 'order-service logs emit HTTP POST timeout to payment.internal after 3000ms', isSupporting: true },
        { id: 'ev-2', text: 'Release v2.4.1 deployment manifest (commit d8f3a9e) increased retry attempts limit', isSupporting: true },
        { id: 'ev-3', text: 'Database latency remained baseline at 4.6ms (excludes DB connection pool exhaustion)', isSupporting: true },
      ],
    },
    alternativeHypotheses: [
      {
        id: 'hyp-2',
        investigationId: 'inv-1042',
        title: 'Database connection pool exhaustion',
        description: 'PostgreSQL max connections limit reached.',
        confidenceLabel: 'LOW',
        probability: 0.14,
        status: 'alternative',
        evidenceItems: [
          { id: 'ev-4', text: 'Postgres connection count at 42/200 (healthy pool depth)', isSupporting: false },
        ],
      },
      {
        id: 'hyp-3',
        investigationId: 'inv-1042',
        title: 'CPU saturation on order-service pods',
        description: 'Kubernetes worker nodes throttled CPU limits.',
        confidenceLabel: 'LOW',
        probability: 0.08,
        status: 'alternative',
        evidenceItems: [
          { id: 'ev-5', text: 'CPU utilization steady at 38% across order-service replica pods', isSupporting: false },
        ],
      },
    ],
    timeline: [
      {
        id: 'tl-1',
        investigationId: 'inv-1042',
        timestamp: '13:30 UTC',
        title: 'Release v2.4.1 deployed to ShopFlow production',
        description: 'Deployment containing commit d8f3a9e deployed to cluster.',
        category: 'deployment',
        severity: 'info',
      },
      {
        id: 'tl-2',
        investigationId: 'inv-1042',
        timestamp: '13:55 UTC',
        title: 'Payment gateway response latency begins increasing',
        description: 'P95 response time rose from 500ms to 2.8s.',
        category: 'anomaly',
        severity: 'warning',
      },
      {
        id: 'tl-3',
        investigationId: 'inv-1042',
        timestamp: '14:02 UTC',
        title: 'HTTP 3000ms timeout threshold exceeded',
        description: 'First HTTP timeout exception logged in order-service.',
        category: 'alert',
        severity: 'critical',
      },
      {
        id: 'tl-4',
        investigationId: 'inv-1042',
        timestamp: '14:04 UTC',
        title: 'Retry amplification cascades to order workers',
        description: 'Increased retry count created 2.5x traffic multiplier.',
        category: 'anomaly',
        severity: 'critical',
      },
      {
        id: 'tl-5',
        investigationId: 'inv-1042',
        timestamp: '14:10 UTC',
        title: 'P95 order latency reaches 3.8s',
        description: 'User-facing checkout slowdown alert triggered.',
        category: 'alert',
        severity: 'critical',
      },
    ],
    evidenceChain: [
      {
        id: 'ec-1',
        stepNumber: 1,
        title: 'Payment gateway latency increase',
        description: 'External payment partner latency rose from 500ms to 3.5s.',
      },
      {
        id: 'ec-2',
        stepNumber: 2,
        title: 'Payment client timeout reached',
        description: 'order-service HTTP calls hit 3s timeout cap.',
      },
      {
        id: 'ec-3',
        stepNumber: 3,
        title: 'Retry amplification',
        description: 'v2.4.1 policy retried failed requests 5 times without exponential backoff.',
      },
      {
        id: 'ec-4',
        stepNumber: 4,
        title: 'Worker thread saturation',
        description: 'All 64 HTTP worker threads blocked waiting for retries.',
      },
      {
        id: 'ec-5',
        stepNumber: 5,
        title: 'User-facing checkout slowdown',
        description: 'P95 order creation duration reached 3.8s with 12.4% HTTP 504 errors.',
      },
    ],
    recommendations: [
      {
        id: 'rec-1',
        category: 'Immediate',
        action: 'Roll back order-service retry attempt limit from 5 to 2 or apply feature flag toggle.',
        reason: 'Eliminate retry amplification traffic multiplier.',
        expectedResult: 'Immediately reduce worker thread pool blocking by 60%.',
        risk: 'Low',
      },
      {
        id: 'rec-2',
        category: 'Investigation',
        action: 'Inspect Stripe payment gateway connection pool and egress NAT gateway metrics.',
        reason: 'Determine root cause of 3.5s response delay on payment partner API.',
        expectedResult: 'Identify whether latency is external or internal network egress.',
        risk: 'Low',
      },
      {
        id: 'rec-3',
        category: 'Long-term',
        action: 'Implement circuit breaker pattern on payment client with exponential backoff & jitter.',
        reason: 'Prevent cascading failures during upstream partner slowdowns.',
        expectedResult: 'Fast-fail payment requests after 2 consecutive timeouts.',
        risk: 'Medium',
      },
    ],
    evidenceGaps: [
      {
        id: 'eg-1',
        gapDescription: 'Payment gateway provider network egress telemetry is missing for 13:45–14:15 UTC.',
        recommendedNextEvidence: 'Upload payment-service-egress.log or Stripe status report.',
        actionPrompt: 'Upload requested evidence',
        impactLevel: 'High',
      },
    ],
    activityTrace: [
      { id: 'act-1', timestamp: '14:04:12', action: 'Established 30-day order latency baseline (320ms)', status: 'done' },
      { id: 'act-2', timestamp: '14:04:15', action: 'Queried order-service & payment-service telemetry', status: 'done' },
      { id: 'act-3', timestamp: '14:04:18', action: 'Correlated release v2.4.1 commit d8f3a9e deployment timestamp', status: 'done' },
      { id: 'act-4', timestamp: '14:04:22', action: 'Evaluated PostgreSQL metrics (excluded DB lock contention)', status: 'done' },
      { id: 'act-5', timestamp: '14:04:26', action: 'Calculated 91% confidence score for primary hypothesis', status: 'done' },
    ],
    createdAt: '2026-08-14T14:04:00Z',
    updatedAt: '2026-08-14T14:25:00Z',
  },
};

export const shopflowKnowledge: KnowledgeDocument[] = [
  {
    id: 'kn-sf-1',
    projectId: 'shopflow',
    name: 'payment-service-runbook.md',
    category: 'Runbooks',
    chunks: 128,
    status: 'Indexed',
    lastUpdated: '2 hours ago',
    summary: 'Standard operating procedures for payment gateway timeout triage and circuit breaker management.',
    tags: ['payment', 'shopflow', 'runbook'],
  },
  {
    id: 'kn-sf-2',
    projectId: 'shopflow',
    name: 'checkout-architecture.md',
    category: 'Architecture',
    chunks: 94,
    status: 'Indexed',
    lastUpdated: '3 days ago',
    summary: 'Order processing pipeline, saga pattern state machine, and service dependency topology.',
    tags: ['checkout', 'architecture'],
  },
  {
    id: 'kn-sf-3',
    projectId: 'shopflow',
    name: 'order-service-debugging.md',
    category: 'Troubleshooting guides',
    chunks: 76,
    status: 'Indexed',
    lastUpdated: '1 week ago',
    summary: 'Debugging guide for HTTP 504 Gateway Timeouts and worker thread pool saturation.',
    tags: ['order-service', 'debugging'],
  },
  {
    id: 'kn-sf-4',
    projectId: 'shopflow',
    name: 'q2-payment-timeout-postmortem.md',
    category: 'Previous incidents',
    chunks: 165,
    status: 'Indexed',
    lastUpdated: 'May 12, 2026',
    summary: 'Post-mortem report covering retry storm incident on payment dependency.',
    tags: ['post-mortem', 'payment'],
  },
];

export const shopflowEvidence: EvidenceItem[] = [
  {
    id: 'ev-sf-1',
    incidentId: 'inc-1042',
    type: 'log',
    title: 'order-service-production.log',
    source: 'Datadog Log Stream',
    fileSize: 42000000,
    status: 'ready',
    rawContent: `2026-08-14T14:03:12Z [ERROR] order-service: HTTP POST https://payment.internal/v1/charge timed out after 3000ms. Retrying (1/5)...`,
    uploadedAt: '14:05 UTC',
  },
  {
    id: 'ev-sf-2',
    incidentId: 'inc-1042',
    type: 'screenshot',
    title: 'dashboard-latency-spike.png',
    source: 'Grafana Snapshot',
    fileSize: 1800000,
    status: 'ready',
    uploadedAt: '14:08 UTC',
  },
];

export const shopflowLogs: LogEvent[] = [
  {
    id: 'log-sf-1',
    evidenceId: 'ev-sf-1',
    timestamp: '2026-08-14T14:03:12Z',
    level: 'ERROR',
    service: 'order-service',
    message: 'HTTP POST https://payment.internal/v1/charge timed out after 3000ms. Retrying (1/5)...',
    stackTrace: `Error: ConnectTimeout: HTTP POST https://payment.internal/v1/charge timed out after 3000ms
    at HttpClient.post (/app/node_modules/http-client/index.js:142:15)
    at OrderProcessor.chargePayment (/app/dist/services/order.js:88:24)`,
    attributes: { timeoutMs: 3000, retryAttempt: 1, maxRetries: 5 },
  },
  {
    id: 'log-sf-2',
    evidenceId: 'ev-sf-1',
    timestamp: '2026-08-14T14:03:15Z',
    level: 'WARN',
    service: 'order-service',
    message: 'Worker thread pool saturation warning: 60/64 active threads waiting on HTTP response',
    attributes: { activeThreads: 60, maxThreads: 64 },
  },
];
