import { Service } from '@/types';

export const shopflowServices: Service[] = [
  {
    id: 'order-service',
    projectId: 'shopflow',
    name: 'order-service',
    health: 'Critical',
    latencyMs: 3800,
    errorRatePercent: 12.4,
    recentIncidentsCount: 1,
    dependencies: [
      { id: 'payment-service', name: 'payment-service', type: 'internal' },
      { id: 'inventory-service', name: 'inventory-service', type: 'internal' },
      { id: 'postgres', name: 'postgres', type: 'database' },
    ],
    recentDeployments: [
      { id: 'dep-sf-101', version: 'v2.4.1 (commit d8f3a9e)', deployedAt: '13:30 UTC', author: 'Alex Chen' },
    ],
    ownerTeam: 'Checkout Core SRE',
  },
  {
    id: 'payment-service',
    projectId: 'shopflow',
    name: 'payment-service',
    health: 'Degraded',
    latencyMs: 3500,
    errorRatePercent: 8.5,
    recentIncidentsCount: 1,
    dependencies: [
      { id: 'payment-gateway', name: 'Stripe Gateway', type: 'external' },
      { id: 'redis', name: 'redis', type: 'cache' },
    ],
    recentDeployments: [
      { id: 'dep-sf-100', version: 'v2.4.0', deployedAt: 'Yesterday 10:00 UTC', author: 'Sarah Jenkins' },
    ],
    ownerTeam: 'Payments Platform',
  },
  {
    id: 'inventory-service',
    projectId: 'shopflow',
    name: 'inventory-service',
    health: 'Healthy',
    latencyMs: 45,
    errorRatePercent: 0.05,
    recentIncidentsCount: 0,
    dependencies: [
      { id: 'postgres', name: 'postgres', type: 'database' },
    ],
    recentDeployments: [],
    ownerTeam: 'Supply & Fulfillment',
  },
  {
    id: 'user-service',
    projectId: 'shopflow',
    name: 'user-service',
    health: 'Healthy',
    latencyMs: 22,
    errorRatePercent: 0.01,
    recentIncidentsCount: 0,
    dependencies: [
      { id: 'redis', name: 'redis', type: 'cache' },
      { id: 'postgres', name: 'postgres', type: 'database' },
    ],
    recentDeployments: [],
    ownerTeam: 'User IAM',
  },
  {
    id: 'postgres',
    projectId: 'shopflow',
    name: 'postgres',
    health: 'Healthy',
    latencyMs: 4,
    errorRatePercent: 0.0,
    recentIncidentsCount: 0,
    dependencies: [],
    recentDeployments: [],
    ownerTeam: 'ShopFlow DB Ops',
  },
  {
    id: 'redis',
    projectId: 'shopflow',
    name: 'redis',
    health: 'Healthy',
    latencyMs: 1,
    errorRatePercent: 0.0,
    recentIncidentsCount: 0,
    dependencies: [],
    recentDeployments: [],
    ownerTeam: 'ShopFlow DB Ops',
  },
];
