import { Incident } from '@/types';

export const finbankIncidents: Incident[] = [
  {
    id: 'inc-finbank-2001',
    code: 'FIN-2001',
    projectId: 'finbank',
    title: 'Ledger reconciliation batch execution drift',
    description: 'End-of-hour financial transaction reconciliation batch jobs taking 4.2s per record due to decimal rounding row locks in v3.1.0 release.',
    severity: 'Critical',
    status: 'Investigating',
    affectedService: 'ledger-service',
    affectedServices: ['ledger-service', 'transaction-service'],
    detectedAt: '12:20 UTC',
    duration: '45m',
    confidence: 88,
    updatedAt: '4m ago',
    reporter: 'FinBank Settlement Monitor',
    environment: 'Production',
  },
  {
    id: 'inc-finbank-2002',
    code: 'FIN-2002',
    projectId: 'finbank',
    title: 'SWIFT payment gateway response timeout',
    description: 'Interbank wire transfer requests timing out on external SWIFT ISO 20022 message validation.',
    severity: 'High',
    status: 'Identified',
    affectedService: 'transaction-service',
    affectedServices: ['transaction-service', 'swift-gateway'],
    detectedAt: '09:40 UTC',
    duration: '2h 10m',
    confidence: 94,
    updatedAt: '22m ago',
    reporter: 'Treasury Ops Alert',
    environment: 'Production',
  },
  {
    id: 'inc-finbank-2003',
    code: 'FIN-2003',
    projectId: 'finbank',
    title: 'Account balance cache invalidation lag',
    description: 'Redis cache TTL delay causing 200ms stale balance reads during concurrent ACH posting runs.',
    severity: 'Medium',
    status: 'Resolved',
    affectedService: 'account-service',
    affectedServices: ['account-service', 'redis'],
    detectedAt: '06:15 UTC',
    duration: '18m',
    confidence: 96,
    updatedAt: '5h ago',
    reporter: 'ACH Audit Agent',
    environment: 'Production',
  },
];
