import { Service } from '@/types';

export const finbankServices: Service[] = [
  {
    id: 'ledger-service',
    projectId: 'finbank',
    name: 'ledger-service',
    health: 'Critical',
    latencyMs: 4200,
    errorRatePercent: 14.8,
    recentIncidentsCount: 1,
    dependencies: [
      { id: 'transaction-service', name: 'transaction-service', type: 'internal' },
      { id: 'postgres', name: 'postgres', type: 'database' },
    ],
    recentDeployments: [
      { id: 'dep-fin-201', version: 'v3.1.0-release', deployedAt: '12:15 UTC', author: 'Marcus Vance' },
    ],
    ownerTeam: 'Core Financial Ledger Team',
  },
  {
    id: 'transaction-service',
    projectId: 'finbank',
    name: 'transaction-service',
    health: 'Degraded',
    latencyMs: 1850,
    errorRatePercent: 6.2,
    recentIncidentsCount: 1,
    dependencies: [
      { id: 'account-service', name: 'account-service', type: 'internal' },
      { id: 'swift-gateway', name: 'SWIFT Network Gateway', type: 'external' },
    ],
    recentDeployments: [
      { id: 'dep-fin-200', version: 'v3.0.8', deployedAt: 'Yesterday 14:00 UTC', author: 'Elena Rostova' },
    ],
    ownerTeam: 'Wire Settlement SRE',
  },
  {
    id: 'account-service',
    projectId: 'finbank',
    name: 'account-service',
    health: 'Healthy',
    latencyMs: 28,
    errorRatePercent: 0.02,
    recentIncidentsCount: 0,
    dependencies: [
      { id: 'redis', name: 'redis', type: 'cache' },
      { id: 'postgres', name: 'postgres', type: 'database' },
    ],
    recentDeployments: [],
    ownerTeam: 'Account IAM',
  },
  {
    id: 'payment-service',
    projectId: 'finbank',
    name: 'payment-service',
    health: 'Healthy',
    latencyMs: 65,
    errorRatePercent: 0.1,
    recentIncidentsCount: 0,
    dependencies: [
      { id: 'transaction-service', name: 'transaction-service', type: 'internal' },
    ],
    recentDeployments: [],
    ownerTeam: 'Treasury Payments',
  },
  {
    id: 'postgres',
    projectId: 'finbank',
    name: 'postgres',
    health: 'Healthy',
    latencyMs: 5,
    errorRatePercent: 0.0,
    recentIncidentsCount: 0,
    dependencies: [],
    recentDeployments: [],
    ownerTeam: 'FinBank DB Ops',
  },
  {
    id: 'redis',
    projectId: 'finbank',
    name: 'redis',
    health: 'Healthy',
    latencyMs: 1,
    errorRatePercent: 0.0,
    recentIncidentsCount: 0,
    dependencies: [],
    recentDeployments: [],
    ownerTeam: 'FinBank DB Ops',
  },
];
