import { Incident } from '@/types';

export const mockIncidents: Incident[] = [
  {
    id: 'inc-1042',
    code: 'INV-1042',
    projectId: 'shopflow',
    title: 'Order creation degradation',
    description: 'Orders are still completing, but the application has become approximately 10x slower during the last hour.',
    severity: 'High',
    status: 'Investigating',
    affectedService: 'order-service',
    affectedServices: ['order-service', 'payment-service'],
    detectedAt: '14:03 UTC',
    duration: '27m',
    confidence: 91,
    updatedAt: '2m ago',
    reporter: 'Datadog Alert Bot',
    environment: 'Production',
  },
  {
    id: 'inc-1041',
    code: 'INV-1041',
    projectId: 'shopflow',
    title: 'Redis connection pool timeout',
    description: 'Transient authorization token verification failures during peak session refresh rates.',
    severity: 'Medium',
    status: 'Identified',
    affectedService: 'user-service',
    affectedServices: ['user-service', 'redis'],
    detectedAt: '11:15 UTC',
    duration: '1h 12m',
    confidence: 84,
    updatedAt: '18m ago',
    reporter: 'PagerDuty On-call',
    environment: 'Production',
  },
  {
    id: 'inc-1040',
    code: 'INV-1040',
    projectId: 'shopflow',
    title: 'Inventory sync batch lock wait threshold',
    description: 'Concurrent stock reservation queries caused temporary row locks on inventory table.',
    severity: 'Low',
    status: 'Resolved',
    affectedService: 'inventory-service',
    affectedServices: ['inventory-service', 'postgres'],
    detectedAt: '08:30 UTC',
    duration: '14m',
    confidence: 98,
    updatedAt: '4h ago',
    reporter: 'DevOps Alertmanager',
    environment: 'Production',
  },
];
