import { Investigation } from '@/types';

export const mockInvestigations: Record<string, Investigation> = {
  'inc-1042': {
    id: 'inv-1042',
    incidentId: 'inc-1042',
    title: 'Order creation degradation',
    status: 'analyzing',
    severity: 'High',
    confidence: 91,
    summary:
      'Order creation latency increased approximately 11.9x beginning around 14:03 UTC. Evidence indicates the primary degradation originates from the payment dependency due to retry amplification following upstream gateway timeouts.',
    impact: {
      affectedFunctionality: 'Checkout & Payment Processing',
      affectedServices: ['order-service', 'payment-service'],
      estimatedImpact: '1,420 checkout sessions delayed, ~12.4% order error rate spike',
      startTime: '14:03 UTC',
      currentDuration: '27m',
    },
    detectedChanges: [
      {
        id: 'mc-1',
        name: 'Order latency',
        baseline: '320 ms',
        current: '3.8 s',
        percentChange: '+1087%',
        isNegative: true,
      },
      {
        id: 'mc-2',
        name: 'Payment latency',
        baseline: '500 ms',
        current: '3.5 s',
        percentChange: '+600%',
        isNegative: true,
      },
      {
        id: 'mc-3',
        name: 'Error rate',
        baseline: '0.7%',
        current: '12.4%',
        percentChange: '+1671%',
        isNegative: true,
      },
      {
        id: 'mc-4',
        name: 'Database query duration',
        baseline: '4.2 ms',
        current: '4.6 ms',
        percentChange: '+9.5%',
        isNegative: false,
      },
    ],
    primaryHypothesis: {
      id: 'hyp-primary',
      investigationId: 'inv-1042',
      title: 'Payment dependency degradation & retry amplification',
      description:
        'Upstream payment provider latency triggered unbounded client-side retries in payment-service, filling connection pools and queuing order processing requests.',
      confidenceLabel: 'HIGH',
      probability: 0.91,
      status: 'primary',
      evidenceItems: [
        { id: 'ev-p1', text: 'Payment latency increased 7x from 500ms to 3.5s', isSupporting: true },
        { id: 'ev-p2', text: 'Order latency increased 11.9x from 320ms to 3.8s', isSupporting: true },
        { id: 'ev-p3', text: 'Database latency remained normal (4.6ms avg)', isSupporting: true },
        { id: 'ev-p4', text: 'Payment retry count increased from 1.2 to 4.8 per transaction', isSupporting: true },
      ],
    },
    alternativeHypotheses: [
      {
        id: 'hyp-alt-1',
        investigationId: 'inv-1042',
        title: 'Database connection pool exhaustion',
        description: 'PostgreSQL queries blocked waiting for free connection pool slots.',
        confidenceLabel: 'LOW',
        probability: 0.14,
        status: 'alternative',
        evidenceItems: [
          { id: 'ev-a1', text: 'PostgreSQL connection utilization at 42% (Normal)', isSupporting: false },
        ],
      },
      {
        id: 'hyp-alt-2',
        investigationId: 'inv-1042',
        title: 'CPU saturation in order-service pods',
        description: 'High CPU utilization causing goroutine scheduling latency in order-service container instances.',
        confidenceLabel: 'LOW',
        probability: 0.08,
        status: 'alternative',
        evidenceItems: [
          { id: 'ev-a2', text: 'Pod CPU usage steady at 38% across 6 replicas', isSupporting: false },
        ],
      },
    ],
    timeline: [
      {
        id: 'tl-1',
        investigationId: 'inv-1042',
        timestamp: '13:30 UTC',
        title: 'Payment latency normal',
        description: 'Average latency steady at 500ms across all gateway routes.',
        category: 'deployment',
        severity: 'info',
      },
      {
        id: 'tl-2',
        investigationId: 'inv-1042',
        timestamp: '13:55 UTC',
        title: 'Latency begins increasing',
        description: 'Upstream gateway P99 latency climbs to 1.8s.',
        category: 'anomaly',
        severity: 'warning',
      },
      {
        id: 'tl-3',
        investigationId: 'inv-1042',
        timestamp: '14:02 UTC',
        title: 'Timeout threshold exceeded',
        description: 'HTTP 504 Gateway Timeouts emitted by payment-service.',
        category: 'alert',
        severity: 'critical',
      },
      {
        id: 'tl-4',
        investigationId: 'inv-1042',
        timestamp: '14:04 UTC',
        title: 'Retries increase',
        description: 'Client retry frequency spikes from 1.2 to 4.8 per transaction attempt.',
        category: 'anomaly',
        severity: 'warning',
      },
      {
        id: 'tl-5',
        investigationId: 'inv-1042',
        timestamp: '14:10 UTC',
        title: 'Order latency reaches 3.8 seconds',
        description: 'P95 order processing duration peaks at 3.8s in order-service metrics.',
        category: 'alert',
        severity: 'critical',
      },
      {
        id: 'tl-6',
        investigationId: 'inv-1042',
        timestamp: '14:15 UTC',
        title: 'User reports degradation',
        description: 'Customer support logs increase in checkout delay tickets.',
        category: 'action',
        severity: 'critical',
      },
    ],
    evidenceChain: [
      {
        id: 'ec-1',
        stepNumber: 1,
        title: 'Payment latency increase',
        description: 'Upstream payment gateway response time increases 7x (500ms → 3.5s).',
      },
      {
        id: 'ec-2',
        stepNumber: 2,
        title: 'Payment timeout',
        description: 'Internal HTTP request timeout threshold (3000ms) breached on payment-service.',
      },
      {
        id: 'ec-3',
        stepNumber: 3,
        title: 'Retries increase',
        description: 'Automatic client retry loops fire up to 5 times sequentially without backoff.',
      },
      {
        id: 'ec-4',
        stepNumber: 4,
        title: 'Order request duration increases',
        description: 'Cumulative retry delays inflate total order execution time from 320ms to 3.8s.',
      },
      {
        id: 'ec-5',
        stepNumber: 5,
        title: 'User-facing slowdown',
        description: 'Customers experience 10x slower checkout button response times.',
      },
    ],
    recommendations: [
      {
        id: 'rec-1',
        category: 'Immediate',
        action: 'Check payment provider health & status dashboard.',
        reason: 'Verify if third-party gateway is undergoing an active service disruption.',
        expectedResult: 'Isolate external vendor fault vs internal networking bug.',
        risk: 'Low',
      },
      {
        id: 'rec-2',
        category: 'Investigation',
        action: 'Review retry configuration in payment-service client SDK.',
        reason: 'Unbounded retries are amplifying latency by 4x during gateway slowdowns.',
        expectedResult: 'Determine if exponential backoff was omitted.',
        risk: 'Low',
      },
      {
        id: 'rec-3',
        category: 'Long-term',
        action: 'Implement bounded retries and circuit breaking on payment route.',
        reason: 'Prevent upstream payment degradation from cascading into order-service thread pool.',
        expectedResult: 'Fail fast within 1s and return graceful degradation response to checkout UI.',
        risk: 'Medium',
      },
    ],
    evidenceGaps: [
      {
        id: 'eg-1',
        gapDescription: 'Payment provider metrics and external gateway error logs are unavailable in trace context.',
        recommendedNextEvidence: 'Upload payment-service logs from 13:30–14:20 UTC or Prometheus gateway metrics export.',
        actionPrompt: 'Upload requested evidence',
        impactLevel: 'High',
      },
    ],
    activityTrace: [
      { id: 'act-1', timestamp: '14:16:02', action: 'Analyzed incident description & user reports', status: 'done' },
      { id: 'act-2', timestamp: '14:16:05', action: 'Established 30-day latency baseline for ShopFlow services', status: 'done' },
      { id: 'act-3', timestamp: '14:16:10', action: 'Queried order-service & payment-service telemetry', status: 'done' },
      { id: 'act-4', timestamp: '14:16:14', action: 'Detected 11.9x order latency increase vs 320ms baseline', status: 'done' },
      { id: 'act-5', timestamp: '14:16:18', action: 'Investigated payment dependency & gateway timeout logs', status: 'done' },
      { id: 'act-6', timestamp: '14:16:22', action: 'Retrieved payment-service-runbook.md documentation', status: 'done' },
      { id: 'act-7', timestamp: '14:16:26', action: 'Compared alternative hypotheses (Postgres, CPU saturation)', status: 'done' },
    ],
    createdAt: '2026-08-14T14:16:00Z',
    updatedAt: '2026-08-14T14:18:00Z',
  },
};
